import { StyleSheet } from 'react-native'

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  safeAreaContainer: {
    width: '100%',
    maxWidth: 500,
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    width: '100%',
    maxHeight: '90%',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  title: {
    fontSize: 18,
    fontWeight: '600',
    color: '#111827',
  },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F3F4F6',
    justifyContent: 'center',
    alignItems: 'center',
  },
  body: {
    flex: 1,
  },
  bodyContent: {
    paddingBottom: 20,
  },
  emptyContainer: {
    padding: 40,
    alignItems: 'center',
  },
  emptyTextMain: {
    fontSize: 16,
    color: '#6B7280',
    marginBottom: 24,
  },
  addButtonContainer: {
    width: '100%',
    gap: 12,
  },
  addButton: {
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  addPracticeButton: {
    backgroundColor: '#10B981',
  },
  addRecordButton: {
    backgroundColor: '#2563EB',
  },
  addButtonIcon: {
    marginRight: 0,
  },
  addButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  entriesContainer: {
    padding: 16,
    gap: 12,
  },
  addRecordSection: {
    padding: 16,
    paddingTop: 24,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
  },
  addRecordSectionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
    marginBottom: 12,
  },
  addRecordButtonContainer: {
    flexDirection: 'row',
    gap: 12,
  },
  addRecordButtonRow: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingVertical: 12,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  addRecordButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
  },
  entryItem: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    borderLeftWidth: 4,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 12,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  entryContentWrapper: {
    flex: 1,
  },
  entryContent: {
    gap: 8,
  },
  entryHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  actionButtons: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
  },
  actionButton: {
    padding: 4,
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: 28,
    minHeight: 28,
  },
  addLogButton: {
    marginTop: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#F3F4F6',
    borderRadius: 6,
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  addLogButtonIcon: {
    marginRight: 0,
  },
  addLogButtonText: {
    fontSize: 12,
    color: '#374151',
    fontWeight: '500',
  },
  entryTypeBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  entryTypeText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  entryTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
  },
  entryPlaceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginTop: 4,
  },
  entryPlace: {
    fontSize: 14,
    color: '#6B7280',
  },
  entryNote: {
    fontSize: 14,
    color: '#374151',
    lineHeight: 20,
  },
  recordDetailContainer: {
    marginTop: 8,
    gap: 4,
  },
  recordRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  recordLabel: {
    fontSize: 13,
    color: '#6B7280',
    fontWeight: '500',
  },
  recordValue: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
  },
  recordNote: {
    fontSize: 13,
    color: '#374151',
  },
  recordEmptyText: {
    fontSize: 13,
    color: '#6B7280',
  },
  expandedContent: {
    paddingTop: 12,
    paddingHorizontal: 12,
    gap: 12,
  },
  practiceLogDetail: {
    backgroundColor: '#F0FDF4',
    borderRadius: 8,
    padding: 12,
    gap: 12,
  },
  practiceContentContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#10B981',
  },
  practiceContentLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#6B7280',
    marginBottom: 4,
  },
  practiceContentText: {
    fontSize: 14,
    color: '#111827',
  },
  practiceContentValue: {
    fontSize: 16,
    fontWeight: '600',
    color: '#059669',
  },
  timeContainer: {
    marginTop: 8,
  },
  timeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  timeHeaderBar: {
    width: 4,
    height: 16,
    backgroundColor: '#10B981',
    borderRadius: 2,
  },
  timeHeaderText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#059669',
  },
  timeTableContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#10B981',
  },
  timeTable: {
    gap: 0,
  },
  timeTableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#D1FAE5',
  },
  timeTableHeaderCell: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 4,
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#10B981',
  },
  timeTableHeaderText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#065F46',
  },
  timeTableLabelCell: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 4,
    justifyContent: 'center',
  },
  timeTableLabelText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#374151',
  },
  timeTableCell: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timeTableValue: {
    fontSize: 12,
    color: '#111827',
  },
  timeTableFastest: {
    color: '#2563EB',
    fontWeight: 'bold',
  },
  timeTableAverageRow: {
    backgroundColor: '#F0FDF4',
  },
  timeTableAverageLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#065F46',
  },
  timeTableAverageValue: {
    fontSize: 12,
    fontWeight: '600',
    color: '#065F46',
  },
  timeTableOverallRow: {
    backgroundColor: '#DBEAFE',
    borderTopWidth: 2,
    borderTopColor: '#2563EB',
  },
  timeTableOverallLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#1E40AF',
  },
  timeTableOverallValue: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#1E40AF',
  },
  loadingText: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
    padding: 16,
  },
  emptyText: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
    padding: 16,
  },
  noteContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  noteLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#6B7280',
    marginBottom: 4,
  },
  noteText: {
    fontSize: 14,
    color: '#374151',
  },
  // RecordDetail用のスタイル
  competitionRecordContainer: {
    marginBottom: 20,
    backgroundColor: '#EFF6FF',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: '#DBEAFE',
  },
  competitionHeader: {
    marginBottom: 12,
  },
  competitionHeaderTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  competitionHeaderLeft: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  competitionHeaderContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  competitionHeaderBar: {
    width: 4,
    height: 20,
    backgroundColor: '#2563EB',
    borderRadius: 2,
    marginRight: 8,
  },
  competitionHeaderTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  competitionHeaderTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#111827',
  },
  competitionHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  competitionHeaderButton: {
    padding: 4,
  },
  competitionHeaderInfo: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 4,
  },
  competitionHeaderInfoItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  competitionHeaderInfoText: {
    fontSize: 12,
    color: '#6B7280',
  },
  competitionHeaderNote: {
    fontSize: 12,
    color: '#6B7280',
    marginTop: 4,
  },
  recordsList: {
    gap: 12,
  },
  recordCard: {
    backgroundColor: '#DBEAFE',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#93C5FD',
  },
  recordContentCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#93C5FD',
    position: 'relative',
  },
  recordCardActions: {
    position: 'absolute',
    top: 8,
    right: 8,
    alignItems: 'flex-end',
    gap: 4,
  },
  recordCardActionsRow: {
    flexDirection: 'row',
    gap: 4,
  },
  recordCardActionButton: {
    padding: 4,
  },
  recordReactionTime: {
    fontSize: 10,
    color: '#6B7280',
  },
  recordInfoGrid: {
    marginTop: 8,
    gap: 8,
  },
  recordInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  recordInfoLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#6B7280',
    minWidth: 50,
  },
  recordStyleValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1E40AF',
    flex: 1,
  },
  recordRelayBadge: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#DC2626',
  },
  recordTimeContainer: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 8,
    flex: 1,
    flexWrap: 'wrap',
  },
  recordTimeValue: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1E40AF',
  },
  recordReactionTimeInline: {
    fontSize: 11,
    color: '#6B7280',
  },
  splitTimesContainer: {
    marginTop: 8,
  },
  splitTimesHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  splitTimesHeaderBar: {
    width: 3,
    height: 16,
    backgroundColor: '#2563EB',
    borderRadius: 2,
    marginRight: 6,
  },
  splitTimesHeaderText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1E40AF',
  },
  splitTimesList: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 8,
    borderWidth: 1,
    borderColor: '#93C5FD',
  },
  splitTimeItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  splitTimeDistance: {
    fontSize: 14,
    fontWeight: '600',
    color: '#374151',
  },
  splitTimeValue: {
    fontSize: 14,
    color: '#1E40AF',
    fontWeight: '600',
  },
  recordNoteContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    padding: 12,
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  recordNoteLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#6B7280',
    marginBottom: 4,
  },
  recordNoteText: {
    fontSize: 14,
    color: '#374151',
  },
  addCompetitionRecordButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#DBEAFE',
    borderRadius: 8,
    padding: 12,
    marginTop: 8,
    borderWidth: 1,
    borderColor: '#93C5FD',
    gap: 6,
  },
  addCompetitionRecordButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1E40AF',
  },
  // EntryDetail用のスタイル
  entrySection: {
    backgroundColor: '#FFF7ED',
    borderRadius: 8,
    padding: 12,
    borderWidth: 1,
    borderColor: '#FED7AA',
    marginTop: 12,
  },
  entrySectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 12,
  },
  entrySectionHeaderEmoji: {
    fontSize: 18,
  },
  entrySectionHeaderTitle: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    color: '#9A3412',
  },
  entrySectionHeaderActionButton: {
    padding: 4,
  },
  entryLoadingText: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
    padding: 8,
  },
  entryEmptyText: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
    padding: 8,
  },
  entryList: {
    gap: 8,
  },
  entryCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 6,
    padding: 12,
    borderWidth: 1,
    borderColor: '#FED7AA',
  },
  entryCardContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  entryCardInfo: {
    flex: 1,
    gap: 6,
  },
  entryCardInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  entryCardInfoLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#9A3412',
    minWidth: 100,
  },
  entryCardInfoValue: {
    fontSize: 14,
    fontWeight: '500',
    color: '#111827',
    flex: 1,
  },
  entryCardInfoValueTime: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
    fontFamily: 'monospace',
  },
  entryCardActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginLeft: 8,
  },
  entryCardDeleteButton: {
    padding: 4,
  },
  competitionHeaderPlace: {
    fontSize: 12,
    color: '#6B7280',
    marginTop: 4,
  },
  competitionHeaderPoolType: {
    fontSize: 12,
    color: '#6B7280',
    marginTop: 2,
  },
  competitionNoteContainer: {
    backgroundColor: '#F9FAFB',
    borderRadius: 6,
    padding: 8,
    marginBottom: 12,
  },
  competitionNoteText: {
    fontSize: 14,
    color: '#374151',
  },
  competitionHeaderActionButton: {
    padding: 4,
  },
})
